### ISSUE TITLE
[components] remove hardcoded backend routes

### ISSUE THREAD

**Issue by severo** [hyparam/hyperparam-cli#22]
https://github.com/hyparam/hyperparam-cli/blob/7f664d5d55f39d7974e490b89112390e64e523df/packages/utils/src/files.ts#L28

https://github.com/hyparam/hyperparam-cli/blob/7f664d5d55f39d7974e490b89112390e64e523df/packages/utils/src/key.ts#L40

**Comment by platypii** [comment]
Over time I think we can convert these pages to just take a url instead of doing "magic" transformations of a local url. So that same-origin urls might look like `/api/store/get?key=example.txt` instead of just `example.txt` and skip the transformations. Slightly uglier url's though. Maybe theres a way to make the utils more generic, but not urgent.

**Comment by severo** [comment]
See https://github.com/hyparam/hyperparam-cli/pull/93
